#!/bin/bash
EV=$1		# главное событие
EVENT=$2	# подсобытие, уточнение события
NICK=$3		# ник или jid

if [ "$4" != "" ]
then
	TEXT=$(cat $4)
	rm  -f $4
else
	TEXT=""
fi

function notify {
gdbus call --session --dest org.freedesktop.Notifications \
	--object-path /org/freedesktop/Notifications  \
	--method org.freedesktop.Notifications.Notify \
	'mcabber_says' 2 '' "$NICK" "$TEXT" [] {} 0
}

case "$EV" in
	"MSG")
		case "$EVENT" in
			"IN")
				mpv ~/.config/mcabber/notify.mp3 &
				notify
				;;
			"MUC")
				FOUND=`echo $TEXT| grep fasterbru`
				if [ "$FOUND" != "" ]
				then
					mpv ~/.config/mcabber/notify.mp3 &
					notify
				fi
				;;
			"OUT")
				;;
		esac
		;;
	"STATUS")
#		case "$EVENT" in
#			"O")	TEXT=online;;
#			"F")	TEXT="free for chat";;
#			"A")	TEXT=away;;
#			"N")	TEXT=n/a;;
#			"D")	TEXT=DND;;
#			"_")	TEXT=offline;;
#			*)		TEXT=$EVENT;;
#		esac
#		gdbus call --session --dest org.freedesktop.Notifications \
#			--object-path /org/freedesktop/Notifications  \
#			--method org.freedesktop.Notifications.Notify \
#			'mcabber_status' 0 '' "$NICK" "$TEXT" [] {} 3000
		;;
	#"UNREAD")
	#	echo $EVENT > ~/.config/mcabber/unread
	#	;;
esac
