#!/bin/bash

TEXT=$(xclip -o -selection primary)
#TEXT=$(xclip -o -selection primary)
if [[ -z "$TEXT" ]]; then
exit 0
else
TEXT1=$(echo $TEXT| tr -d '\n')
#TIME=$(date +%s%N | cut -b1-13)
TEXT2=$(echo $TEXT1| trans -b :ru)
#TIME=$((`date +%s%N | cut -b1-13` - $TIME))
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify \
'translater' 0 0 "$TEXT1 \n" "$TEXT2" [] {} 40000
#'translater' 0 0 "$TEXT1 \n" "$TEXT2\n${TIME}ms" [] {} 40000

fi
