# --------------------------------------------------
# terminal
.terminal-links: &terminal-links
    bat:
        target: "{{.GitRoot}}/configs/terminal/bat"
        link: "{{.Home}}/.config/bat/config"
    tmux:
        target: "{{.GitRoot}}/configs/terminal/tmux"
        link: "{{.Home}}/.tmux.conf"
    zsh:
        target: "{{.GitRoot}}/configs/terminal/zshrc"
        link: "{{.Home}}/.zshrc"
    starship:
        target: "{{.GitRoot}}/configs/terminal/starship.toml"
        link: "{{.Home}}/.config/starship.toml"
    kitty:
        target: "{{.GitRoot}}/configs/terminal/kitty.conf"
        link: "{{.Home}}/.config/kitty/kitty.conf"
    ranger:
        target: "{{.GitRoot}}/configs/terminal/ranger"
        link: "{{.Home}}/.config/ranger/rc.conf"
    less:
        target: "{{.GitRoot}}/configs/terminal/lesskeys"
        link: "{{.Home}}/.lesskey"
    tealdeer:
        target: "{{.GitRoot}}/configs/terminal/tealdeer.toml"
        link: "{{.Home}}/.config/tealdeer/config.toml"

    # Git
    git-config:
        target: "{{.GitRoot}}/configs/git/gitconfig"
        link: "{{.Home}}/.gitconfig"
    git-ignore:
        target: "{{.GitRoot}}/configs/git/gitignore_global"
        link: "{{.Home}}/.gitignore_global"

    # Nvim
    nvim:
        target: "{{.GitRoot}}/configs/nvim/init.vim"
        link: "{{.Home}}/.config/nvim/init.vim"
    nvim-coc:
        target: "{{.GitRoot}}/configs/nvim/coc-settings.json"
        link: "{{.Home}}/.config/nvim/coc-settings.json"
    nvim-layout:
        target: "{{.GitRoot}}/configs/nvim/keymap/custom_ru.vim"
        link: "{{.Home}}/.config/nvim/keymap/custom_ru.vim"

    snippets:
        target: "{{.GitRoot}}/configs/nvim/UltiSnips/"
        link: "{{.Home}}/.local/share/nvim/UltiSnips/s"

    # Misc
    xprofile:
        target: "{{.GitRoot}}/configs/misc/xprofile"
        link: "{{.Home}}/.xprofile"
    Xresources:
        target: "{{.GitRoot}}/configs/misc/Xresources"
        link: "{{.Home}}/.Xresources"
    scripts:
        target: "{{.GitRoot}}/scripts/"
        link: "{{.Home}}/.local/bin/"
    trizen:
        target: "{{.GitRoot}}/configs/misc/trizen.conf"
        link: "{{.Home}}/.config/trizen/trizen.conf"

# --------------------------------------------------
# desktop
.desktop-links: &desktop-links
    # Qutebrowser
    qute:
        target: "{{.GitRoot}}/configs/qutebrowser/config.py"
        link: "{{.Home}}/.config/qutebrowser/config.py"
    qute-style:
        target: "{{.GitRoot}}/configs/qutebrowser/style.css"
        link: "{{.Home}}/.config/qutebrowser/style.css"
    qute-draw:
        target: "{{.GitRoot}}/configs/qutebrowser/theme/draw.py"
        link: "{{.Home}}/.config/qutebrowser/theme/draw.py"
    qute-marks:
        target: "{{.GitRoot}}/configs/qutebrowser/quickmarks"
        link: "{{.Home}}/.config/qutebrowser/quickmarks"
    qute-gm:
        target: "{{.GitRoot}}/configs/qutebrowser/greasemonkey"
        link: "{{.Home}}/.local/share/qutebrowser/greasemonkey"
    qute-clear:
        target: "{{.GitRoot}}/configs/qutebrowser/my_scripts/clear.js"
        link: "{{.Home}}/.config/qutebrowser/my_scripts/clear.js"

    # Polybar
    polybar:
        target: "{{.GitRoot}}/configs/polybar/config.ini"
        link: "{{.Home}}/.config/polybar/config.ini"
    polybar-startup:
        target: "{{.GitRoot}}/configs/polybar/startup"
        link: "{{.Home}}/.config/polybar/startup"

    # Keyboard
    keyboard:
        target: "{{.GitRoot}}/configs/keyboard/keymap/config"
        link: "{{.Home}}/.config/xkb/keymap/config"
    keyboard-dv:
        target: "{{.GitRoot}}/configs/keyboard/symbols/dv_layout"
        link: "{{.Home}}/.config/xkb/symbols/dv_layout"
    keyboard-ru:
        target: "{{.GitRoot}}/configs/keyboard/symbols/ru_layout"
        link: "{{.Home}}/.config/xkb/symbols/ru_layout"

    # Gtk
    gtk-css:
        target: "{{.GitRoot}}/configs/gtk/gtk.css"
        link: "{{.Home}}/.config/gtk-3.0/gtk.css"
    gtk-settings:
        target: "{{.GitRoot}}/configs/gtk/settings.ini"
        link: "{{.Home}}/.config/gtk-3.0/settings.ini"
    gtk2-rc:
        target: "{{.GitRoot}}/configs/gtk/gtkrc-2.0"
        link: "{{.Home}}/.gtkrc-2.0"

    # Desktop
    picom:
        target: "{{.GitRoot}}/configs/desktop/picom.conf"
        link: "{{.Home}}/.config/picom.conf"
    rofi-style:
        target: "{{.GitRoot}}/configs/rofi/style.rasi"
        link: "{{.Home}}/.config/rofi/style.rasi"
    mouse-theme:
        target: "{{.GitRoot}}/configs/desktop/mouse_index.theme"
        link: "{{.Home}}/.icons/default/index.theme"
    xdg-dirs:
        target: "{{.GitRoot}}/configs/desktop/user-dirs.dirs"
        link: "{{.Home}}/.config/user-dirs.dirs"
    mime:
        target: "{{.GitRoot}}/configs/desktop/mimeapps.list"
        link: "{{.Home}}/.config/mimeapps.list"

    # Services
    services:
        target: "{{.GitRoot}}/services/"
        link: "{{.Home}}/.config/systemd/user"

    # Misc
    pulseaudio:
        target: "{{.GitRoot}}/configs/misc/pulse"
        link: "{{.Home}}/.config/pulseaudio-ctl/config"
    zathura:
        target: "{{.GitRoot}}/configs/misc/zathurarc"
        link: "{{.Home}}/.config/zathura/zathurarc"

# --------------------------------------------------
# commands
.commands: &commands
    flameshot:
        input: "{{.GitRoot}}/configs/desktop/flameshot.ini"
        output: "{{.Home}}/.config/flameshot/flameshot.ini"
        command: "sed \"s~%HOMEDIR%~$HOME~g\" {{.Input}} > {{.Output}}"

    qute_link:
        input: "{{.GitRoot}}/configs/qutebrowser/qute_link.desktop"
        output: "{{.Home}}/.local/share/applications/qute_link.desktop"
        command: "sed \"s~%HOMEDIR%~$HOME~g\" {{.Input}} > {{.Output}}"
    gpg-agent:
        input: "{{.GitRoot}}/configs/misc/make-gpg-agent.sh"
        output: "{{.Home}}/.gnupg/gpg-agent.conf"
        command: "bash {{.Input}} {{.Output}}"

# --------------------------------------------------
# templates
.instance: &instance
    input: "{{.GitRoot}}/configs/instance.tmpl"
    output: "{{.Home}}/.instance"

# rofi
.rofi_default: &rofi_default
    input: "{{.GitRoot}}/configs/rofi/config.tmpl"
    output: "{{.Home}}/.config/rofi/config.rasi"
    data:
        dpi: 1

.rofi_note: &rofi_note
    <<: *rofi_default
    data:
        dpi: 0

# dunst
.dunst_default: &dunst_default
    input: "{{.GitRoot}}/configs/desktop/dunst.tmpl"
    output: "{{.Home}}/.config/dunst/dunstrc"
    data:
        scale: 0
        fontSize: 13
        width: 500

.dunst_note: &dunst_note
    <<: *dunst_default
    data:
        scale: 1
        fontSize: 10
        width: 700

# i3
.i3_template: &i3_template
    input: "{{.GitRoot}}/configs/desktop/i3.tmpl"
    output: "{{.Home}}/.config/i3/config"

.i3_data_note: &i3_data_note
    telegramPosition: "1348 96"
    telegramSize:     "525 700"
    dropdownPosition: "18 46"
    dropdownSize:     "1884 500"
    rangerPosition:   "18 46"
    rangerSize:       "1884 500"
    quteEditorSize:   "675 336"

.i3_data_home: &i3_data_home
    <<: *i3_data_note
    telegramPosition: "2872 468"
    telegramSize:     "580 740"
    dropdownPosition: "978 352"
    rangerPosition:   "978 352"
    monitors:
        left: "DisplayPort-0"
        right: "DVI-D-0"

i3_data_work: &i3_data_work
    << : *i3_data_note
    monitors:
        left: "DP-2"
        right: "HDMI-3"

# --------------------------------------------------
# Insnances
instances:
    home:
        links:
            <<: [*terminal-links, *desktop-links]
        commands: *commands
        templates:
            instance:
                <<: *instance
                data: home
            i3:
                <<:  *i3_template
                data: *i3_data_home
            dunst:
                <<: *dunst_default
            rofi:
                <<: *rofi_default

    work:
        links:
            <<: [*terminal-links, *desktop-links]
        commands: *commands
        templates:
            instance:
                <<: *instance
                data: work
            i3:
                <<:  *i3_template
                data: *i3_data_work
            dunst:
                <<: *dunst_default
            rofi:
                <<: *rofi_default

    note:
        links:
            <<: [*terminal-links, *desktop-links]
        commands: *commands
        templates:
            instance:
                <<: *instance
                data: note
            i3:
                <<:  *i3_template
                data: *i3_data_note
            dunst:
                <<: *dunst_note
            rofi:
                <<: *rofi_note
