all:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  hosts:
    varch:
      ansible_ssh_private_key_file: .vagrant/machines/varch/virtualbox/private_key
    vubuntu:
      ansible_ssh_private_key_file: .vagrant/machines/vubuntu/virtualbox/private_key
