#!/bin/sh

export TERMINAL=termite

xset m 1/1 0
setxkbmap -model pc105 -layout us,ru -variant altgr-intl, winkey -option terminate:ctrl_alt_bksp, grp:caps_toggle, grp_led:scroll, compose:menu, lv5:rwin_switch_lock
xset b off

TOP="#50405a"
BOT="#0a0a0a"

hsetroot -addd "$TOP" 1 -addd "$BOT" 2 -gradient 1
