#!/bin/sh

export TERMINAL=termite
export LC_ALL=en_US.UTF-8
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

if grep -q home ~/.instance; then
  xrandr --output DVI-D-1 --auto --primary --output DP-1 --auto --noprimary --right-of DVI-D-1
fi

if grep -q work ~/.instance; then
  xrandr --output HDMI-2 --primary --output DP-1 --left-of HDMI-2
fi

xset m 1/1 0
xset r rate 200 30
setxkbmap -model pc105 -layout us,ru -variant altgr-intl, winkey -option terminate:ctrl_alt_bksp, grp:caps_toggle, grp_led:scroll, compose:menu, lv5:rwin_switch_lock
xkbcomp -I$HOME/.config/xkb ~/.config/xkb/keymap/config $DISPLAY -w 0
xset b off

COLOR=#6A6379

hsetroot -solid "$COLOR"
