#!/bin/bash
INTERFACE="${BLOCK_INSTANCE:-wlan0}"

[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 99 / 70) }')
SSID=$(iwconfig $INTERFACE | grep SSID | cut -d \" -f 2)

echo "<span font='Fantasque sans mono'>"$SSID $QUALITY"</span>"
echo "<span font='Fantasque sans mono'>"$SSID $QUALITY"</span>"

if [[ $QUALITY -le 30 ]]; then
	echo "FF0000"
fi
