#!/bin/bash

pkill -SIGUSR1 dunst
file1=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)

scrot -z -d0  "$file1"
convert "$file1" -blur 0x4 "$file1"

convert -spread 4 -swirl 5 -emboss 1  "$file1" "$file1"
convert -spread 2 -composite -gravity center "$file1" ~/.local/bin/logo.png "$file1" 

i3lock -n -i "$file1" -c 000000

trap "rm '$file1' && pkill -SIGUSR2 dunst" EXIT

