#!/bin/bash

# Script open template project with two panes.
# left directory  - startup directory for left pane.
# right directory - startup directory for right pane.
# session name    - name for tmux session.
# code file       - main project file.

left_directory="$1"
right_directory="$2"
session_name="${3:-$(basename $left_directory)}"
code_file="$4"

# check
if [ -z "$left_directory" ]; then
  echo "left directory is required!"
  exit 1
fi

if [ -z "$right_directory" ]; then
  echo "right directory is required!"
  exit 1
fi

# make two tmux panes
if [ -n "$TMUX" ]; then
  if [ "$(tmux list-panes | wc -l)" -gt "1" ]; then
    tmux new-window
    tmux split-window -h
  else
    tmux split-window -h
  fi
else
  tmux new-session -d -s "$session_name"
  tmux split-window -h
fi

tmux select-pane -t 0
tmux send-keys "cd $left_directory" Enter
tmux send-keys "clear" Enter

if [ -n "$code_file" ]; then
  sleep 0.4
  tmux send-keys "n $code_file" Enter
fi

tmux select-pane -t 1
tmux send-keys "cd $right_directory" Enter
tmux send-keys "clear" Enter
tmux select-pane -t 0

if [ -z "$TMUX" ]; then
  tmux attach-session -d -t "$session_name"
fi
