#!/bin/bash
NAME=screen-$(date +%d:%m:%y-%H:%M:%S).png
FILE=$HOME/screens/$NAME

# do screenshot
import -quality 100 $FILE

# copy to clipboard
xclip -selection clipboard -t `file -b --mime-type $FILE` -i $FILE

# send notification
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify \
'screenshoter' 0 '' "$FILE" "screenshot area saved and copied to clipboard" [] {} 4000
