#!/bin/bash

BUFFER_TEXT=$(xclip -o -selection primary)

if [[ -z "$BUFFER_TEXT" ]]; then
  exit 0
fi

SOURCE_TEXT=$(echo $BUFFER_TEXT| tr -d '\n')
TEXT_TO_REQUEST=$(echo $SOURCE_TEXT| sed 's/\ /%20/g')
REQUEST="https://translate.yandex.net/api/v1.5/tr.json/translate?key=trnsl.1.1.20170225T104218Z.65b3640e352caab9.17b01b96d5bf3d6cc5af809ebf0d8a4729a4f6c9&lang=ru&text="

TRANSLATED_TEXT=$(curl -s "$REQUEST$TEXT_TO_REQUEST" | jq -r '.text[]')

gdbus call --session --dest org.freedesktop.Notifications --object-path \
  /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify \
  'translater' 0 0 "$SOURCE_TEXT \n" "$TRANSLATED_TEXT" [] {} 40000

