#!/bin/bash
NAME=screen-$(date +%d:%m:%y-%H:%M:%S).png
if [ -n "$1" ]
then
FILE_PATH=$HOME/Pictures/$1/
else
FILE_PATH=$HOME/Pictures/Screens/
fi
scrot -s "$FILE_PATH/$NAME"
xclip -selection clipboard -t `file -b --mime-type $FILE` -i $FILE
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify \
'screenshoter' 0 '' "$FILE" "screenshot area saved and copied to clipboard" [] {} 4000
#'screenshoter' 0 '' "$NAME" "screenshot area saved and copied to clipboard" [] {} 4000
