#!/bin/bash

TEXT=$(xclip -o -selection primary)
if [[ -z "$TEXT" ]]; then
exit 0
else
TEXT1=$(echo $TEXT| tr -d '\n')
TEXT2=$(echo $TEXT1| sed 's/\ /%20/g')
#TIME=$(date +%s%N | cut -b1-13)
TEXT3=$(curl -s "https://translate.yandex.net/api/v1.5/tr.json/translate?key=trnsl.1.1.20170225T104218Z.65b3640e352caab9.17b01b96d5bf3d6cc5af809ebf0d8a4729a4f6c9&lang=ru&text=$TEXT2" | jq -r '.text[]')
#TIME=$((`date +%s%N | cut -b1-13` - $TIME))
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify \
'translater' 0 0 "$TEXT1 \n" "$TEXT3" [] {} 40000
#'translater' 0 0 "$TEXT1 \n" "$TEXT2\n${TIME}ms" [] {} 40000
fi
