#!/bin/python
import sys

def get_from_file(filename):
    with open(filename, 'r') as file:
        return file.read()[:-1]

def exit(icon, text, color = ""):
    final_text = "<span font='xos4 Terminus 13'>{} {}</span>".format(icon, text)
    print(final_text)
    print(final_text)
    print(color)
    sys.exit(0)

if __name__ == "__main__":
    status = get_from_file("/sys/class/power_supply/BAT1/status")
    charge_now = get_from_file("/sys/class/power_supply/BAT1/charge_now")
    charge_full = get_from_file("/sys/class/power_supply/BAT1/charge_full")
    charge = int(100 * int(charge_now) / int(charge_full))

    if status == "Full":
        lighting = "&#xf0e7;"
        plug     = "&#xf1e6;"
        exit(lighting, plug)

    elif status == "Unknown":
        unknown = "&#xf128;"
        exit(unknown, "")

    elif status == "Discharging":
        color = ""
        if charge > 80:
            icon = "&#xf240;"
        elif charge > 60:
            icon = "&#xf241;"
        elif charge > 40:
            icon = "&#xf242;"
        elif charge > 20:
            icon = "&#xf243;"
            color = "#CC2222"
        else:
            icon = "&#xf244;"
            color = "#FF0000"

        exit(icon, str(charge) + '%', color)

    elif status == "Charging":
        lighting = "&#xf0e7;"
        exit(lighting, str(charge) + '%')

    else:
        no_found = "&#xf00d; &#xf240;"
        exit(no_found, "")
