#!/bin/bash

declare -i SUM=0 NEWSUM=0 BUSY=0 NEWBUSY=0


exec 3</proc/stat
read -u 3 _ TUSR TNICE TSYS TIDLE TIOWAIT TIRQ TSOFTIRQ TSTEAL TGUEST TGUESTNICE
exec 3>&-
BUSY=$((TUSR + TNICE + TSYS + TIRQ + TSOFTIRQ + TSTEAL + TGUEST + TGUESTNICE))
SUM=$((BUSY + TIDLE + TIOWAIT))

sleep 1

exec 3</proc/stat
read -u 3 _ TUSR TNICE TSYS TIDLE TIOWAIT TIRQ TSOFTIRQ TSTEAL TGUEST TGUESTNICE
exec 3>&-
NEWBUSY=$((TUSR + TNICE + TSYS + TIRQ + TSOFTIRQ + TSTEAL + TGUEST + TGUESTNICE))
NEWSUM=$((NEWBUSY + TIDLE + TIOWAIT))

CPU=$(( ( $NEWBUSY - $BUSY ) * 100 / ( $NEWSUM - $SUM ) ))


echo $CPU
echo $CPU

TEMP=`echo $CPU | cut -d '.' -f1`
if [[ $TEMP -ge 75 ]]; then
    echo "#FF4444"
elif [[ $TEMP -ge 50 ]]; then
    echo "#FFC077"
fi
