#!/bin/bash

MEM=`awk '
 /^MemTotal:/ {total = $2}
 /^MemFree:/ {free = $2}
 /^Buffers:/ {free += $2}
 /^Cached:/ {free += $2}
 END {
	print (1-free/total)*100
}
' /proc/meminfo | cut -d "." -f1`

RET="<span font='xos4 Terminus 13'>$MEM</span>"
echo $RET
echo $RET

if [[ $MEM -ge 90 ]]; then
    echo "#FF6666"
elif [[ $MEM -ge 80 ]]; then
    echo "#FFC077"
fi
