#!/bin/bash

case $BLOCK_BUTTON in
  3) pactl set-sink-mute 0 toggle;;
  4) pactl -- set-sink-volume 0 +5% ;;
  5) pactl -- set-sink-volume 0 -5% ;;
esac

if [ `ponymix is-muted; echo $?` = 1 ] ; then
  TEXT=`ponymix get-volume`%
else
  TEXT="&#xf05e;"
fi

RET="<span font='xos4 Terminus 13'>$TEXT</span>"
echo $RET
echo $RET
