#!/bin/sh

export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
export GCC_COLORS=true
export LC_ALL=en_US.UTF-8
export TERMINAL=kitty

if grep -q home ~/.instance; then
 xrandr --output DVI-D-0 --auto --primary --output DisplayPort-0 --auto --left-of DVI-D-0
fi

xset m 1/1 0
xset r rate 200 30
xkbcomp -I$HOME/.config/xkb ~/.config/xkb/keymap/config $DISPLAY -w 0
xset b off

COLOR=#595C64

hsetroot -solid "$COLOR"
