#!/bin/bash
# Script allow select template project with preview and open it

# preview functions
main_files="fd -tf --max-depth=2 '(main.cpp|main.qml|main.py)'"
preview_function="bat --color=always \$($main_files {})"
ls_function="ls --color=always -l {}"

# list of template projects sorted by time
template_projects=$(fd -td . ~/tmp/ --max-depth=1 | xargs ls -dt | tr " " "\n")

# select template project from list
project=$(echo "$template_projects" | fzf --preview-window=right:65% --preview="$preview_function ; $ls_function")
if [ -z "$project" ]; then
  echo "choosing is close"
  exit 1
fi
echo "$project is choosed"

# get build directory if exist
build_path=$(fd -td build $project | head -1)
build_path="${build_path:-$project}"

# get main file
main_file=$(fd -tf --max-depth=2 '(main.cpp|main.qml|main.py)' $project | head -1)

# open project
open_template_project "$project" "$build_path" "$(basename $project)" "$main_file"
